code/modules/reagents/Chemistry-Reagents/Medicine-Reagents.dm, html/changelogs/Pyko - Atropine.yml
=> Fixes Atropine not metabolizing

code/modules/clothing/head/misc.dm, code/modules/clothing/head/misc_special.dm
Added "flags = BLOCKHAIR" to Ushanka and cardborg helmet.
Any ideas of other hats that should hide hair?
=> More hair covering hats.

code/game/objects/items/weapons/explosives.dm, code/modules/food&drinks/food/snacks_pizza.dm
Fixes https://github.com/HippieStationCode/HippieStation13/issues/1060
For pizzabox, dont know any other item that causes c4 overlay to go away.
=> Invisible C4 at pizzabox fix

code/modules/food&drinks/kitchen machinery/deep_fryer.dm, code/modules/mob/living/carbon/human/update_icons.dm, code/modules/mob/living/carbon/update_icons.dm
Fixes https://github.com/HippieStationCode/HippieStation13/issues/1143
=> Deepfried clothes Fix

code/game/objects/buckling.dm, code/modules/mob/living/living.dm, code/modules/mob/living/living_defines.dm, code/modules/power/cable.dm, code/modules/recycling/disposal-unit.dm
Fixed  no gravity animation reseting pixel_y for mobs that get buckled.
Made noose cause no damage if there is no gravity.
Fixes: https://github.com/HippieStationCode/HippieStation13/issues/1672
=> Gravity animation fix & noose depending on gravity

code/modules/research/designs/autolathe_designs.dm, html/changelogs/Spacedong - beartraps.yml
Janitor only has 2 and if they're lost they're gone for good. They have a high cost of metal to make so you can't spam the fuck outta em.
=> Added bear traps to autolathe (hacked).

code/modules/clothing/suits/armor.dm, html/changelogs/Spacedong - Riotarmorfix.yml
yeah lets not have hulks running around with 90% resistance to melee at top speed yes k thanks
=> Fixes riot armor slowdown.

code/game/gamemodes/objective_items.dm, code/game/objects/structures/crates_lockers/closets/secure/scientist.dm, code/modules/clothing/suits/armor.dm, code/modules/research/designs/weapon_designs.dm, html/changelogs/Esumlogos.yml
Lowers the activation rate by half and adds a slowdown effect. As discussed in https://github.com/HippieStationCode/HippieStation13/pull/1872 and https://github.com/HippieStationCode/HippieStation13/pull/1881
It already has had head approval and a code review, I was asked to squash all the commits into one which was impossible without deleting the repository (good thing there wasn't much on it).
=> Nerfs the reactive teleport armor.

code/game/objects/items/weapons/implants/implant_chem.dm
=> Fixes chemical implant bug, no longer self activatable

code/game/gamemodes/game_mode.dm
ask carbon, hes the cuck here.
=> carbon is a cuck

code/datums/mutations.dm
Re adds carbons fix for monkeys not turning to humans.
https://github.com/HippieStationCode/HippieStation13/pull/1692/files
=> Monkey fix

code/game/objects/structures/plasticflaps.dm
Fixes https://github.com/HippieStationCode/HippieStation13/issues/1977
=> Plasticflaps Fix

_maps/map_files/generic/z2.dmm
Removes these useless tard windows so people can access them from all angles for more meme carnage slaughter fun. 
https://vgy.me/F73NyS.png
=> Removes the windows blocking the liberation stations from the front on Centcomm.

code/game/objects/structures/crates_lockers/closets/secure/security.dm
Self explanatory. Captain should have HUD's.
=> Adds HUDglasses to the Captains Locker

code/datums/uplink_item.dm, code/game/objects/items/weapons/implants/implant_mindslave.dm, code/game/objects/items/weapons/storage/uplink_kits.dm
Adds Greater Mindslave Implants. 
They're like Mindslave Implants except they last forever. Cost 16 TC. Don't work on Traitors or Changelings.
I also fixed up the messages you receive when being mindslaved. They were NOT very good, and looked bad when you were actually implanted.
=> Greater Mindslave Implants

code/datums/diseases/zombie.dm, code/game/gamemodes/zombie/zombie.dm, code/modules/mob/living/simple_animal/hostile/zombie.dm
commented out most of the zombie stuff.
Pretty sure its not this tho.
=> Restrart bug finding 1 - Zombies

code/datums/diseases/zombie.dm, code/game/gamemodes/zombie/zombie.dm, code/modules/mob/living/simple_animal/hostile/zombie.dm
=> Restart test fix 1

code/modules/reagents/Chemistry-Recipes/Medicine.dm, html/changelogs/chemicals.yml
Ported from
https://github.com/tgstation/-tg-station/pull/16515
=> Re adds the recipes for Bicard, Kelotane, AntiTox, and Tricord

code/game/objects/items/weapons/cigs_lighters.dm, html/changelogs/Kierany9 - Cigarretes.yml
Works exactly like plasma and welding fuel cigarettes, nitroglycerin explodes with the same power as plasma and Blackpowder is 2/3rds the strength of Plasma.
=> Cigarettes with Blackpowder and Nitroglycerin now explode when lit

code/modules/power/supermatter/supermatter.dm, html/changelogs/Spacedong - supermatterfix.yml
- fixes #2567 in which people would get kicked in a mech or closet when bumped into the shard
- replaced an instance of del with qdel
=> fixes a priority supermatter bug

code/modules/mob/living/carbon/human/species.dm, html/changelogs/Kierany9 - Bugfixes2.yml
Fixes https://github.com/HippieStationCode/HippieStation13/issues/2462 holy shit crystal dismemberment broke so much jesus this has been driving me up the wall for fucking ages
=> Even more bugfixes

code/modules/mob/living/carbon/human/species_types.dm, html/changelogs/Spacedong - catdisabilities.yml
Catbeasts now start with epilepsy, stupidity, coughing, and tourettes in addition to clumsiness.
=> Catbeasts now spawn with crippling disabilities

code/modules/mob/living/carbon/human/examine.dm, code/modules/reagents/reagent_containers/pill.dm
=> Typo fixes

SQL/tgstation_schema.sql
=> carbon told me to make this pr i have no idea why or what it does

code/game/objects/items/weapons/storage/uplink_kits.dm, html/changelogs/Kierany9 - Bugfixes3.yml
admittedly i caused this one but oh well
- Fixed a bug where the energy dagger inside one of the traitor bundles would not spawn.
=> Yet another bugfix

code/datums/uplink_item.dm, html/changelogs/Kierany9 - WresleCQC.yml
This was previously in the King of the Disk PR and didn't have much to do with the gamemode so I took it out.
Reduces the price of Wrestling and CQC from 12 TC to 5 and 7 TC respectively. I have no idea what Crystal was thinking when he made these 12 each, both are fun memey 1v1 items, neither of them can compete with the Esword or Power Fist in terms of usability or power.
=> Reduces the price of the Wrestling Belt and CQC

code/modules/reagents/Chemistry-Reagents.dm
=> Chemistry Bugfix [Already][Extremely important][Top Priority][Fire whoever codechecked the pr]

code/game/gamemodes/changeling/powers/strained_muscles.dm, html/Kierany9 - Codewords.yml, html/changelogs/Kierany9 - Bugfixes4.yml
Fixes https://github.com/HippieStationCode/HippieStation13/issues/2737
The deleted file is a misplaced changelog of mine that was getting on my nerves.
=> A bugfix once more

code/ATMOSPHERICS/components/unary_devices/Freezer.dm, html/changelogs/Kierany9 - Powersinks.yml
(fixes https://github.com/HippieStationCode/HippieStation13/issues/1710 causing freezers to drain power as well as being able to cool gases below 0 degrees kelvin, and granting them negative pressure)
(this does not nerf actual power sinks)
=> Nerfs power sinks

code/game/objects/items/weapons/storage/dakis.dm
honestly these people didn't do anything noteworthy to warrant their place in the game code and as such they don't deserve to be immortalized here
=> Removes references of players in dakimakuras

html/changelogs/Spacedong - dakilog.yml
=> changelog for my previous daki PR

code/game/objects/items.dm
god damn this went unnoticed for years
=> learn to spell mothrefukcer

code/game/objects/items/weapons/storage/book.dm
fixes issue #2890
EDIT: it was carbon
=> Fixes healing with chaplains bible

code/modules/ducttape/crafts.dm
makeshift armor description says it slows you down but it doesn't anymore
=> minor description fix for makeshift armor

code/datums/mutations.dm, code/modules/mob/living/carbon/emote.dm, code/modules/mob/living/carbon/human/life.dm, code/modules/mob/living/carbon/human/species_types.dm, code/modules/surgery/organs/teeth.dm
its spelled "tajaran" not "tarajan" you fuckin idiot whoever coded this
=> fixes giant tajaran species typo

code/datums/mutations.dm, code/modules/mob/living/carbon/emote.dm, code/modules/mob/living/carbon/human/life.dm, code/modules/mob/living/carbon/human/species_types.dm, code/modules/surgery/organs/teeth.dm
merge this then merge the other invisible cat fix then update the server
=> Revert "Revert "fixes giant tajaran species typo""

code/game/machinery/doors/airlock.dm, html/changelogs/Spacedong - hardhats.yml
the most important PR and the pinnacle of my coding skill
=> hard hats now protect you from headbutting airlocks while retarded

code/modules/reagents/Chemistry-Reagents/Medicine-Reagents.dm, html/changelogs/Spacedong - Ephedrinenerf.yml
Anti Stuns Are Gay Part 2: Electric Boogaloo
=> Nerfs ephedrine

code/game/machinery/vending.dm
god fucking damn it how can you get something so simple so wrong
=> holy fuck you'd think coders didn't go to elementary school or something

code/modules/clothing/under/miscellaneous.dm, html/changelogs/Spacedong - adminsuit.yml
thats pretty much it, it looks like the old one and I got rid of the cybernetic fluff bullshit
=> changed the new admin jumpsuit's description and sprite to mimic the old one and because im autistic

code/game/machinery/spaceheater.dm, html/changelogs/Spacedong - spaceheaterfix.yml
Fixes #3227
Tested in-game and it works.
=> Space heater UI will now properly update

code/modules/mob/living/carbon/human/emote.dm, html/changelogs/Spacedong - assfartnoise.yml
=> oh shit what was that noise 

code/modules/food&drinks/food/snacks.dm, code/modules/mob/living/carbon/human/human_defense.dm, code/modules/mob/living/carbon/human/species.dm, code/modules/reagents/reagent_containers/pill.dm
=> respect my pronouns

_maps/map_files/TgStation/tgstation.2.1.3.dmm, _maps/map_files/generic/z4.dmm, code/modules/reagents/Chemistry-Reagents/Toxin-Reagents.dm, code/modules/reagents/reagent_containers/glass.dm, code/modules/reagents/reagent_containers/spray.dm, code/modules/research/designs/weapon_designs.dm
"The IUPAC adopted the spelling sulfur in 1990, as did the Royal Society of Chemistry Nomenclature Committee in 1992."
=> get your shit together coders you're expected to know the science behind the things you code

code/game/objects/structures/crates_lockers/closets/job_closets.dm, html/changelogs/Spacedong - chembiosuit.yml
weird, thought chemists always had these, guess not
=> The wardrobe locker in Chemistry now contains 2 standard biosuits

code/modules/clothing/under/miscellaneous.dm
=> fixed some bullshit

code/modules/mob/living/silicon/ai/ai.dm, html/changelogs/Spacedong - AiCommandFix.yml
=> Moved "Toggle Camera Lights" to AI commands tab

code/modules/power/gravitygenerator.dm
In theoretical physics, the graviton is a hypothetical elementary particle that mediates the force of gravitation in the framework of quantum field theory.
=> its spelled "graviton"
