- code/game/objects/items/robot/robot_items.dm
It now costs 300 power instead of 30 power, which is basically free.
For comparison, the sec borg's stun baton costs 1000 power. Why a tool specifically designed to incapacitate humans with nonlethal electric shock costs 30 TIMES MORE POWER than the stun arm, I don't know.
Quite frankly the stun arm makes no sense. Realistically it'd just char the person to a crisp before it shocks them.
> Nerfs borg stun arm

- code/game/objects/items/weapons/implants/implant_chem.dm
Now they can no longer be self activated under any circumstances, only through the console.
> Fixes last chemical implant bug

- code/game/objects/objs.dm
Closes the GUI for any storage that is burned.
Fixes https://github.com/HippieStationCode/HippieStation13/issues/1903
> Burnt storages and GUI

- code/modules/recycling/conveyor2.dm
Made conveyor switch update the conveyor belts soon after the map is loaded.
Meaning that you just have to mapedit the switch on/off, and it will pass it on to linked belts soon after the map is loaded, instead of having to edit the switch and all the belts.
Technically a fix to disposals conveyors starting off even tho the switch is on, but also a mapping feature.
> Conveyor switch

- code/modules/reagents/Chemistry-Reagents/Drug-Reagents.dm
- code/modules/reagents/Chemistry-Reagents/Medicine-Reagents.dm
- code/modules/reagents/Chemistry-Recipes/Drugs.dm
- html/changelogs/Kierany9 - Meth Balance.yml
These changes have been made to bring meth in line with the other stimulants and makes Bath Salts actually worth using either as a poison or stimulant as well as fixing its recepie. Currently there is no reason to use any other stimulant(except Adrenal Implants) over meth, as it is one of the easiest to make(can make 80u in about 30 seconds) and has no side effects of any severity. Crank is much weaker, harder to make and is more harmful, Ephendrine is weaker but much safer and Bath Salts has so many side effects it's not even funny.
- Nerfs Methamphetamine and Bath Salts, causing a stun and brain, stamina and toxin damage (scales with how long the drug was in the player's system) once the drug wears off.
- Lowers overdose threshold on both drugs to 15.
- Brain damage only takes effect …
> Methamphetamine + Bath Salts Nerf

- code/modules/reagents/Chemistry-Reagents/Drug-Reagents.dm
- code/modules/reagents/Chemistry-Reagents/Medicine-Reagents.dm
Quick fix to a couple of things I managed to mess up with my last PR that nobody caught. Adds a 5-cycle(10 in the case of Ephedrine) minimum for the stuns of these chemicals to kick in, as adding a very low dose to a syringe gun would provide an instant 5-second stun as well as heavy stamina damage. Also changed the stamina damage a bit for balancing purposes. Crank now does 20 Stamina damage and Meth does 35.
> Anti-stun update quickfix

- code/modules/mob/living/carbon/human/species.dm
- html/changelogs/Kierany9 - Melee Combat Balance.yml
I've made this PR because apparently somebody thought it was a good idea to add an instant-win RNG to melee fights. If you don't know, there is a chance equal to the brute damage of the weapon used to KO the target for 20 seconds when aiming for the head, or knocking them down for five seconds when aiming for the body. Both of these pretty much guarantee a victory in a fight and are completely random.
Knockouts when aiming for the head have been replaced with concussions, which deal a very brief (0.5 second) stun, brain damage based on weapon strength and cause 10 seconds of dizzyness, which causes erratic movement, making it harder for you to run or to fight but not impossible ~~like the fucking bullshit 20 second knockout dear god fuck you cultist i was fully auged how did you fucking …
> Replaces knockouts and knockdowns in melee combat

- code/__HELPERS/names.dm
- html/Kierany9 - Codewords.yml
Codewords are pretty fucking useless. But they don't have to be. The only reason why they're so bad is because they use extremely specific words designed with HRP-style rounds in mind and stick out like a sore thumb here on Hippie. This PR simply changes all the available codewords for a vocabulary that is more in-tune with our server. So keep an ear out, tator-tots, we've got some new codewords coming in!
- Replaces words such as "courageous", "pride" and "loyalty" with more common ones such as "valid", "xenos" and "honk"
- Added gamemode names (nuke ops, cult, revs, lings) as uncommon codewords to give Security a push in the wrong direction
- Drinks have been removed as possible codewords
- Added a properly abbreviated list of locations (No more "Aft Solars Maintinence" thank god)
- Did …
> Making Codewords Useable

- code/datums/uplink_item.dm
- code/modules/clothing/gloves/miscellaneous.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/living.dm
- html/changelogs/Kierany9 - Pickpocket Gloves.yml
Adds Pickpocket Gloves to the Traitor Uplink for ~~3~~ 4 TC. These gloves triple your stripping speed, remove any alerts the target may get to having their equipment stripped and places any stolen items straight into your hand. While this means you can only take off one item at a time since it fills your hand, by the time they notice it'll probably be too late and you got off scott-free with their ID, egun or nuke disk. Not the most powerful of items since it relies on you getting extremely close to well-armed people to get the most out of it but generally great for harassment and theft, especially when combined with soap and other slips.
> Pickpocket Gloves Traitor Item

- code/modules/power/smes.dm
Fixes issue #2281 where hitting a SMES with any object would display an admin-log saying it was deconstructed.
> Fixed SMES bug

- code/game/objects/structures/girders.dm
Fixes #2186 They now grow under the girders instead.
> Fixed resin weeds growing on top of girders

- code/game/mecha/equipment/weapons/weapons.dm
- code/modules/research/designs/mecha_designs.dm
- code/modules/research/designs/mechfabricator_designs.dm
- html/changelogs/Kierany9 - Mech Balance.yml
You wanna know how much damage the mech LMG does? A light machine gun that's mounted on a war robot designed to kill you as efficiently as possible while tanking a metric fuckton of damage?
Five
Yep, five.
**FIVE!!!**
Anyway, this PR basically buffs some of the mech weapons to stop them from being a laughing stock and make them actually worth using, most notably the Incendinary Carbine AKA Hades(Now fires incendinary slugs instead of a single dragonsbreath pellet, increasing its damage from 5 to 20), the LMG AKA Ultra AC 2(Fires a 6-shot burst with bullets dealing 10 damage each instead of a 3-shot burst of 5 damage 80 stamina bullets), the Shotgun AKA Scattershot(Increased pellets fired from 4 to 6 and tightened the spread slightly for maximum hallway devastation) and the laser and pulse …
> Mech buffs

- code/game/machinery/camera/tracking.dm
Ported over from /tg/. Some faggot a long time ago added artificial lag on the AI camera tracking. /tg/ removed it there a few months ago, and now I'm removing it here.
> Removes artificial lag on AI tracking

- code/game/verbs/who.dm
- code/modules/admin/admin.dm
- code/modules/admin/admin_verbs.dm
Admins can ghost and see a shit ton of round information and it's not even logged. It's very easy to get away with. In the same vein, an Admin can open the player panel, hover over someone's name and see if they are a traitor or not, absolutely no way to get caught. This fixes it, so if a non observing admin ghosts, opens the player panel, or shows the player panel of a specific player, other admins are notified.  That's all.
> Adds admin logs anytime a non observing admin ghosts or views the player panel

- code/modules/admin/admin_verbs.dm
trials can use it now
i should rephrase that this doesn't move the location of the verbs it just allows trial admins to see it
> Moves 'fix breach' and 'clean air' verbs to regular admin panel

- code/game/gamemodes/shadowling/shadowling.dm
- code/game/gamemodes/shadowling/shadowling_abilities.dm
- code/game/gamemodes/shadowling/special_shadowling_abilities.dm
- html/changelogs/Logos - Shadowling.yml
Shadowlings are OP. Everyone knows it.
changes:
- tweak: "Shadow Walk cooldown time increased to 45 seconds."
- tweak: "You can no longer use Shadow Walk after being stunned, you
have to wait till the stun wears off to use it."
- tweak: "You can no longer use certain shadowling abilities while in
Shadow Walk."
- tweak: "Shadowlings no longer are stun immune while in the dark,
instead they just have their stuns reduced."
- rscdel: "Shadowlings can no longer use the spell Destroy Engines."
> Balances Shadowlings

- code/game/gamemodes/gang/recaller.dm
- html/changelogs/Spacedong - dominatorfix.yml
Fixes issue #2606 where a dominator could be placed in a bluespace shelter/another area in space.
> Dominator area fix

- code/game/mecha/equipment/weapons/weapons.dm
- code/modules/research/designs/mecha_designs.dm
- code/modules/research/designs/mechfabricator_designs.dm
- html/changelogs/Kierany9 - Mech Balance2.yml
The gateway broke the server just as my exam season started and I never noticed that a bunch of PRs got reverted including https://github.com/HippieStationCode/HippieStation13/pull/2249 so it's back. The only difference between this PR and the old one is that the LMG needs Combat 5 instead of Combat 6. Other than that, everything is the same.
> Mech buffs: 'I didn't realize everything got reverted' edition

- code/datums/uplink_item.dm
- code/modules/paperwork/photography.dm
- html/changelogs/Kierany9 - Spirit Camera.yml
Adds the Spirit Camera to the Traitor Uplink for all civilian jobs(Assistant, Librarian, Lawyer, Chaplain, Clown and Mime). This camera allows you to input the (real) name of any living mob and it will return a photo of them in their current location. If the person is dead or the name you put in was invalid, the photo will be of yourself instead. After taking a spirit photo (regardless of whether it worked or not), the camera will be on cooldown for sixty seconds. It can take up to 4 photos before needing a new film. It also works like a normal camera and can be toggled between modes by any antagonist who clicks on it.
> Spirit Camera Traitor Item

- code/game/gamemodes/nuclear/nuclear.dm
- code/game/gamemodes/nuclear/nuclear_challenge.dm
- code/game/machinery/computer/syndicate_shuttle.dm
- html/changelogs/Kierany9 - Declaration.yml
- Nuke Ops can now customize the message broadcast to the station when declaring war.
- The declaration tool now tells you how long you have left to decide when the activation prompt shows up.
- Fixed a bug where nuke ops could wait indefinitely before declaring war.
- Fixed the nuke ops having less time than they should to declare war.
> Nuke Ops can customize their declaration of war

- code/modules/reagents/Chemistry-Holder.dm
- html/changelogs/Kierany9 - Runtime.yml
For the record, I only have a vague idea of how what I did fixes the runtime, but it stops addictions from spewing out runtimes every tick and addictions now work properly. **Although I'd rather have this merged *after* we can isolate the cause of, and fix, the server stability problems we're having right now.** Also, I'd suggest reducing the duration of addictions as they are extremely crippling, have no cure and can take people out of the round for at least 10 minutes, or kill them if they can't get to the medbay on time. Not doing it here because I don't want a runtime fix to get boged with features that'll end up needing HA approval.
> Fixes a runtime with addictions

- code/datums/uplink_item.dm
- code/game/objects/items/weapons/storage/briefcase.dm
- code/modules/projectiles/guns/projectile/saw.dm
- code/modules/projectiles/guns/projectile/sniper.dm
- html/changelogs/Kierany9 - Newcops.yml
Minor nuke ops weapon changes that remove bloat and hopefully make these weapons more useful.
- **Sniper Rifles now dismember targeted limbs when using standard or high-explosive ammo.** Can't remove the head or chest for obvious reasons.
- **Replaced haemorrhage rounds with high-explosive rounds.** These deal 40 damage with no armour penetration(as opposed to 70 damage and 50 AP) but explode in a 1-tile radius(3x3 area) similar to the gyrojet pisol. Like regular rounds, these can delimb and break through walls.
- All sniper magazines now hold five shots regardless of type (Standard held 6, Sleepy held 3, Penetrator held 5).
- Sniper bundle now contains a HE magazine and costs 2 TC more (20 -> 22)
- Decreased the price from 16 TC to 14 TC. However, the price of ammo has gone up (Standard: …
> Nuke Ops weapon tweaks

- code/game/gamemodes/traitor/king_disk.dm
- html/changelogs/Kierany9 - BugfixesKotD.yml
- Fixes a bug where where the disk would not grant extra telecrystals when stored in bags.
- Fixes a bug where mindslaves holding the disk would receive a message about gaining extra TC instead of whoever implanted them.
- The PDA uplink now automatically refreshes when gaining extra TC.
> King of the Disk major bugfixes

- code/game/gamemodes/traitor/king_disk.dm
- html/changelogs/Kierany9 - KotDplayers.yml
While King of the Disk is most definitely designed for higher populations of players, we're rarely hitting 45 players at roundstart, meaning that it almost never gets played. And from the few rounds I've seen, it's been far less of a murderfest than Double Agents or Revolution, which need 25 and 20 players minimum respectively.
> Reduces King of the Disk's minimum playercount by 10

- code/modules/clothing/clothing.dm
- code/modules/clothing/shoes/magboots.dm
- code/modules/clothing/shoes/miscellaneous.dm
- code/modules/mob/living/carbon/human/species.dm
- html/changelogs/Kierany9 - MediumStyle.yml
- Adds Stomping. Jackboots, Magboots and Combat boots deal extra brute damage on downed targets and when active, Magboots can perform a windup attack that deals 45 brute as long as the target stays down for four seconds.
- Melee weapons do not deal stamina damage on prone opponents and instead deal the full amount of brute damage.
- Fists deal more brute damage and less stamina damage (0.5 to 5 brute and 2.5 to 7.5 stamina instead of 0.5 to 2 brute and 3.5 to 9 stamina).
- Syndicate Magboots have one less slowdown when active (2 -> 1)
> Stomping + Melee Combat Tweaks

- code/modules/projectiles/guns/projectile/sniper.dm
- code/modules/reagents/Chemistry-Reagents/Drug-Reagents.dm
- code/modules/reagents/Chemistry-Reagents/Medicine-Reagents.dm
- html/changelogs/Kierany9 - Bugfixes5.yml
This was never supposed to be a thing. Oops.
Useless feature I added to try and balance it out but in practise it just makes morphine annoying to use.
these ez antistuns are a tad too good.
If your lethal drug is going to have any positive effects, please don't make them useless. I accidentally overshadowed it with Heroin so here's something to redeem that.
> Minor bugfixes and balancing

- code/modules/reagents/Chemistry-Reagents.dm
- html/changelogs/Kierany9 - stuns.yml
Basically, after I reworked antistun chemicals, they allowed you to get up from a stun immediately after X ticks of not being stunned. However, after initial testing by our local powergaming expert showed that this was somewhat underpowered, I added a second stun resist that would allow you to resist stuns immediately if you spent 3 ticks unstunned after the timer hit X, _and said stun resist would only set the timer back to X, meaning you could ignore taser-strength stuns every three seconds regardless of the effectiveness of the chemical_. I think you can all see what went wrong here and why I'm removing this feature.
> Removes second stun resist from antistuns

- code/modules/mob/living/carbon/human/species.dm
- html/changelogs/Kierany9 - Hallucinations.yml
The max health hallucination now makes your stamina appear full as well. This also prevents you from gauging your HP from your stamina bar while using Morphine, Heroin or Miner's Salve.
> More realistic hallucinations

- code/controllers/configuration.dm
- code/game/gamemodes/abduction/abduction.dm
- code/game/gamemodes/changeling/traitor_chan.dm
- code/game/gamemodes/game_mode.dm
- code/game/gamemodes/gang/gang.dm
- code/game/gamemodes/gang/recaller.dm
- html/changelogs/Kierany9 - MaxPlayersAndGangStuff.yml
Admins can still force these modes above the maximum, they simply won't appear in secret. This is intended for modes that don't run well enough in highpop, as they don't pose enough of a threat to the station. **Abductors now have a maximum playercount of 45** and they have been given a special scaling to acomodate this.
- Traitorling: 0 -> 25
- Gang: 20 -> 25
The minimum number of gangs has been increased from 2 to 3. Extra gangs now have a chance equal to the number of players to appear at the 38 and 50 player marks. The maximum number of gangs is now five. This is why I've slightly bumped the minimum playercount. Because having two gangs and one getting fucked roundstart is never fun.
>let's give the rigatoni a c20 for less price than an uzi amirite oh and how about a detvolver at the …
> Gang Tweaks, Traitorling Playercount and Maximum Playercounts

- code/game/machinery/atmoalter/portable_atmospherics.dm
- html/changelogs/Spacedong - connectorfix.yml
> Canisters wrenched to connectors will now update their icons properly if the connector they were attached to is deleted.

- code/datums/uplink_item.dm
- code/game/machinery/syndicatebomb.dm
- html/changelogs/Spacedong - blastco.yml
Blastco anti-burglar payloads will now instantly detonate upon sensing a mob in the armory. They will despawn once blastco is bought legitimately. Fixes issue #3254. Please codecheck this before merging.
> blastco armory is now completely burglarproof (TM)
